### ISSUE TITLE
Generally mark required fields for an initial registration and/or extract the missing fields from the exception thrown by the registry and mark them

### ISSUE THREAD

**Issue by THuppke** [openbase/bco.registry.editor#2]
When creating a UnitGroup, the fields LocationId and Label are required. Yet there is no warning when pressing "Apply" without providing them. Instead the created instance is deleted.

**Comment by pLeminoq** [comment]
Now the created instance remains in the editor if the registration fails.
Marking required fields remains a task.

**Comment by DivineThreepwood** [comment]
This issue can be closed, since we are using protobuf 3 where required fields are no longer supported for such reasons.
