### ISSUE TITLE
Wrong initialization of device positions (rotation)

### ISSUE THREAD

**Issue by lilischroeder** [openbase/bco.registry.editor#31]
When a device that has no position yet is clicked and new values for PlacementConfig->Position->Translation are entered, a dialog window asks if missing values should be intialized. 
After initalization, the values for PlacementConfig->Position->ROTATION are **NaN** which causes an exception in Bcozy because the units' transformation cannot be calculated.

**Comment by pLeminoq** [comment]
Should be fixed by openbase/jul@105ee0b665fed1a143d48d9ba52c4682ba631692. It was yet another bug because of required fields in protobuf which do not support default values. This caused all values in the quaternion to be 0 which results in NaN for roll, pitch and yaw values.
