### ISSUE TITLE
uint64 always displayed as date

### ISSUE THREAD

**Issue by THuppke** [openbase/bco.registry.editor#32]
The native type uint64 is always displayed as a date in the registry editor.
For the indices in type FloorCeilingEdge which is now part of shape of every UnitConfig for example, this is not wanted.

**Comment by pLeminoq** [comment]
Should be fixed by commit 6012d3388633645a4fd60a6cd4d8d51470ba020a. These types are now only represented as a date if they are inside a timestamp.
