### ISSUE TITLE
Registry tabs disappear after adding new units.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry.editor#37]
e.g. if a new user is registered the user tab is just showing the loading animation after pressing apply. The entries disappear und only restarting the registry editor solve the problem.

There is no exception or error message printed.

**Comment by pLeminoq** [comment]
Did you do anything special? I just tried to reproduce this by starting bco and the registry-editor. Then I registered a new user but the bug you mentioned did not occur.

**Comment by DivineThreepwood** [comment]
Maybe this is a race condition and was caused by registering the unit via a wifi connection. I will prioritize this issue again if there is a way identified to reproduce it.

**Comment by DivineThreepwood** [comment]
Now we can reproduce the issue by removing a scene entry.

**Comment by pLeminoq** [comment]
Sometimes isDataAvailable returned false for VirtualRegistryRemotes after the initial sync. This should be fixed by commit openbase/bco.registry@3db9458dbe889d4bd5e15ed2a6e4994db33bbe08.

**Comment by DivineThreepwood** [comment]
At least fixed since the registry.editor reimplementation.
