### ISSUE TITLE
The loading symbol does not disappear if the updated entry by the registry matches the one displayed

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.registry.editor#38]

**Comment by DivineThreepwood** [comment]
Why is the registry-editor still waiting for new updates instead just listening to the rpc future?
Since the SyncFuture has been implemented an returning get should include all needed changes or am I wrong?

**Comment by pLeminoq** [comment]
This was a duplication of #33 because in a new version of the registry editor already replaced the buttons with a progress indicator. With the old bug this one is fixed as well.
