### ISSUE TITLE
Remove outdated code of "old registry editor"

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry.editor#44]
* [x] remove outdated code
* [x] create issues for missing features, e.g. id to config jump

**Comment by pLeminoq** [comment]
Remaining code has been removed in commit 8c8616a0c197937b7f40d884d1e0f80f2d9dd65a.
Issue for id config jump already exists: #41 
If more features of the old registry editor come to mind which are missing just open a new issue for them.
