### ISSUE TITLE
Placement transformation and rotation values not properly updated.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry.editor#6]
Placement transformation and rotation values (x,y,z,...) are not updated within the unit config type and therefore not updated in the registry after modifications in the registry-editor.

**Comment by pLeminoq** [comment]
This bug is fixed by a jul update.
The ProtoBufFieldProcessor in jul has a method to check if only some required field in a builder are set. This method had a bug which would return a false value in some cases which caused the registry editor to reset these values.
